# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20160927_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='apt_images'),
        ),
    ]
